model:
  checkpoint: models/asr/whisper-medium/runs/whisper-medium-fa/final
  processor: openai/whisper-medium
  language: Persian
  task: transcribe

data:
  root_dir: data
  datasets:
    - cv-corpus-25.0
    - data/FarsSpon_train_dev
    - data/fleurs-normalized
  sample_rate: 16000
  split: test

eval:
  output_dir: models/asr/whisper-medium/evals
  name: whisper-medium-fa-test
  batch_size: 1
  num_workers: 4
  device: auto
  generation_max_length: 225
  max_label_tokens: 448
  eval_accumulation_steps: 1
